### ISSUE TITLE
promise support

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/multipipe#41]

**Comment by aks-** [comment]
Hi! I was thinking of implementing it but not quite sure how promises fit in there. Can you please give more context?

**Comment by okv** [comment]
Hi, there.
I think that's about returning promise if callback is no passed.
That would be great.
Currently I'm doing something like `const multipipeAsync = pify(multipipe);` every time.

**Comment by okv** [comment]
I realized that promisified multipipe could be used only in particular case - when waiting for the finish of streams chain and result stream is not needed. But I don't know how this could be done in general case because multipipe returns stream (always return promise that resolves to stream doesn't look good).

**Comment by juliangruber** [comment]
What about

```js
const stream = pipe(a, b, c)
await stream.finished()
```
